// Regenerates ../testdata/engine-vectors.json (repo root) from lib/heatwaveEngine.ts.
//
// The TypeScript engine is the source of truth; the Go port in
// backend/internal/engine must reproduce these vectors. Run this only when the
// TS engine's behaviour changes on purpose, then update the Go port to match:
//
//   bun run vectors
//
import { writeFileSync } from "node:fs";
import {
  assessHeatwave,
  buildDailyRiskForecast,
  calculateHeatIndex,
  computeTrendAnomaly,
  evaluateHeatRisk,
  HEAT_RISK_THRESHOLDS_C,
} from "../lib/heatwaveEngine";
import type { DailyWeather } from "../lib/types";

const { caution, extremeCaution, danger, extremeDanger } = HEAT_RISK_THRESHOLDS_C;

// Heat index: a grid that crosses the simple-formula cutoff and both humidity
// adjustment bands, plus out-of-range humidity to exercise clamping.
const heatIndex: { tempC: number; humidity: number; expected: number }[] = [];
for (let tempC = 0; tempC <= 50; tempC += 2.5) {
  for (let humidity = 0; humidity <= 100; humidity += 10) {
    heatIndex.push({ tempC, humidity, expected: calculateHeatIndex(tempC, humidity) });
  }
}
for (const [tempC, humidity] of [
  [30, -5],
  [30, 120],
  [35, 5],
  [28, 90],
  [27, 85.5],
  [43.3, 12.9],
] as const) {
  heatIndex.push({ tempC, humidity, expected: calculateHeatIndex(tempC, humidity) });
}

// Risk tiers: every threshold exactly, just below it, and the 2-day Danger rule.
const riskCases: { tempC: number; apparentTempC: number; daysMaxTemp?: number[] }[] = [
  { tempC: 20, apparentTempC: 20 },
  { tempC: 30, apparentTempC: caution - 0.01 },
  { tempC: 30, apparentTempC: caution },
  { tempC: 35, apparentTempC: extremeCaution - 0.01 },
  { tempC: 35, apparentTempC: extremeCaution },
  { tempC: 38, apparentTempC: danger - 0.01 },
  { tempC: 40, apparentTempC: danger },
  { tempC: 40, apparentTempC: danger, daysMaxTemp: [] },
  { tempC: 40, apparentTempC: danger, daysMaxTemp: [danger] },
  { tempC: 40, apparentTempC: danger, daysMaxTemp: [danger, danger] },
  { tempC: 40, apparentTempC: danger, daysMaxTemp: [danger + 3, danger - 0.5, danger] },
  { tempC: 40, apparentTempC: danger, daysMaxTemp: [30, danger, danger + 2, danger + 1] },
  { tempC: 40, apparentTempC: danger, daysMaxTemp: [danger, danger, danger - 1] },
  { tempC: 45, apparentTempC: extremeDanger - 0.01, daysMaxTemp: [44, 44, 44] },
  { tempC: 50, apparentTempC: extremeDanger },
  { tempC: 50, apparentTempC: extremeDanger + 10, daysMaxTemp: [10] },
];
const evaluate = riskCases.map((c) => ({
  ...c,
  expected: evaluateHeatRisk(c.tempC, c.apparentTempC, c.daysMaxTemp),
}));

// Full assessment (heat index, consecutive days, warning flag, message text).
const assessCases = [
  { tempC: 24, apparentTempC: 25, humidity: 50, dailyApparentMax: [26, 27, 25, 28, 26, 27, 26] },
  { tempC: 33, apparentTempC: 35, humidity: 60, dailyApparentMax: [34, 36, 37, 35, 36, 38, 37] },
  { tempC: 37, apparentTempC: 40, humidity: 55, dailyApparentMax: [38, 39, 40, 39, 38, 40, 39] },
  { tempC: 40, apparentTempC: 42, humidity: 45, dailyApparentMax: [41, 42, 43, 41.5, 42, 44, 45] },
  { tempC: 40, apparentTempC: 42, humidity: 45, dailyApparentMax: [41, 30, 31, 32, 33, 34, 42] },
  { tempC: 40, apparentTempC: 42, humidity: 45, dailyApparentMax: [] },
  { tempC: 47, apparentTempC: 55, humidity: 20, dailyApparentMax: [50, 52, 55, 56, 54, 53, 55] },
].map((c) => ({ ...c, expected: assessHeatwave(c.tempC, c.apparentTempC, c.humidity, c.dailyApparentMax) }));

const trendInputs: number[][] = [
  [],
  [30],
  [30, 30, 30, 30],
  [30, 31, 30, 35],
  [30, 31, 30, 31],
  [35, 34, 33, 30],
  [30, 31],
  [20, 21, 20, 21.5, 20.5, 21, 22],
];
const trend = trendInputs.map((dailyTempMax) => ({ dailyTempMax, expected: computeTrendAnomaly(dailyTempMax) }));

// Seven-day forecast: a rising heatwave, so the tier walks up through the rolling series.
const daily: DailyWeather = {
  time: ["2026-05-01", "2026-05-02", "2026-05-03", "2026-05-04", "2026-05-05", "2026-05-06", "2026-05-07"],
  temperature2mMax: [34, 36, 39, 41, 42, 44, 40],
  temperature2mMin: [24, 25, 26, 27, 28, 28, 27],
  apparentTemperatureMax: [33, 36.5, 39, 41, 42.5, 55, 40],
  uvIndexMax: [8, 9, 10, 11, 11, 12, 10],
  precipitationSum: [0, 0, 0, 0, 0, 0, 1.2],
};
const mild: DailyWeather = {
  time: ["2026-10-01", "2026-10-02", "2026-10-03"],
  temperature2mMax: [27, 28, 26],
  temperature2mMin: [20, 21, 20],
  apparentTemperatureMax: [28, 29, 27],
  uvIndexMax: [6, 6, 5],
  precipitationSum: [0, 3, 10],
};
const dailyRiskForecast = [daily, mild].map((d) => ({ daily: d, expected: buildDailyRiskForecast(d) }));

const vectors = {
  _comment:
    "Generated by frontend/scripts/generate-engine-vectors.ts from frontend/lib/heatwaveEngine.ts. Do not edit by hand. Consumed by frontend/lib/heatwaveEngine.test.ts and backend/internal/engine/engine_test.go.",
  thresholdsC: HEAT_RISK_THRESHOLDS_C,
  heatIndex,
  evaluateHeatRisk: evaluate,
  assessHeatwave: assessCases,
  trendAnomaly: trend,
  dailyRiskForecast,
};

writeFileSync(new URL("../../testdata/engine-vectors.json", import.meta.url), JSON.stringify(vectors, null, 1) + "\n");
console.log(
  `wrote testdata/engine-vectors.json: ${heatIndex.length} heat index, ${evaluate.length} risk, ` +
    `${assessCases.length} assessment, ${trend.length} trend, ${dailyRiskForecast.length} daily forecast vectors`,
);
